name: yt-shorts-automation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: sudo apt update && sudo apt install -y ffmpeg
      - run: pip install edge-tts requests

      - run: python script.py
      - run: python voice.py
      - run: python captions.py
      - run: python download_stock.py
      - run: python build_video_ffmpeg.py

      - run: zip final.zip final.mp4

      - uses: actions/upload-artifact@v4
        with:
          name: youtube-short
          path: final.zip
